### ISSUE TITLE
React Lamp

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/genie#19]
Create a genie lamp that's a react component

**Comment by jeffscottward** [comment]
Very interested. Building a bitcoin trading platform which has quite a huge amount of UI elements.

**Comment by kentcdodds** [comment]
If I have time, maybe I'll get to it, but I wouldn't be hopeful for it. A PR would be totally welcome :-) Thanks for expressing interest! Encourages me to work on it.
