### ISSUE TITLE
Angular Lamp customise template

### ISSUE THREAD

**Issue by philjones88** [kentcdodds/genie#24]
Hi,

One feature I was interested in doing was customising the HTML template that shows up to include helpful messages about key short cuts. Mostly this is driven by the Genie like feature in Slack, as shown below.

![image](https://cloud.githubusercontent.com/assets/677167/9379600/6694f604-4722-11e5-84ed-be270cb4aee9.png)

Would this be a PR of interest to you or do you have another mechanism I couldn't see to achieve a custom genie template?

**Comment by kentcdodds** [comment]
I'm guessing you found [this](https://github.com/kentcdodds/genie/tree/master/src/lamps/angular#custom-templates) :-)
