### ISSUE TITLE
is there a react/redux example that you might know of?

### ISSUE THREAD

**Issue by sw-yx** [kentcdodds/genie#33]
i know this is a long shot, i'm just kinda fishing for examples for inspiration as i evaluate genie for use at Netlify 😅

**Comment by sw-yx** [comment]
things i found (not at all the same category since genie does some magic fuzziness):

- https://github.com/greena13/react-hotkeys
- https://github.com/jaywcjlove/react-hotkeys#readme
	- https://wangchujiang.com/hotkeys/
- https://github.com/avocode/react-shortcuts

**Comment by sw-yx** [comment]
alright what i want doesnt exist. as i feared. i hope i have time to make it...

**Comment by kentcdodds** [comment]
Hey my friend. Check this out: https://codesandbox.io/s/jrlkrxwgl

genie + downshift = 😇

**Comment by kentcdodds** [comment]
Also, you may be interested to know that codesandbox uses geniejs 😉 https://github.com/codesandbox/codesandbox-client/blob/c6758b23f7416d371b4d2212ffb8766bf0db96eb/packages/app/src/app/pages/Sandbox/QuickActions/index.js

**Comment by kentcdodds** [comment]
Another fun fact is that it's also using downshift

**Comment by sw-yx** [comment]
full stack kentcdodds!

**Comment by kentcdodds** [comment]
Want to make a PR to link to it from the readme?
